image: python:latest

stages:
  - test
  - diffs
  - screenshot
  - model
  - convert

before_script:
  - git clone --depth 1 https://gitlab.com/kicad/libraries/kicad-library-utils $CI_BUILDS_DIR/kicad-library-utils
  - git config --global --add safe.directory $(realpath .)

klc-check:
  stage: test
  needs: []
  when: always
  allow_failure:
    exit_codes:
     - 2  # KLC checks have warnings
  only:
    refs:
      - merge_requests
    changes:
      - "**/*.kicad_mod"
      - "fp-lib-table"
  script:
      # Don't let Gitlab force return code 1 on error
    - set +e
    - $CI_BUILDS_DIR/kicad-library-utils/tools/gitlabci/check_footprints.sh
  artifacts:
    reports:
      metrics: metrics.txt
      junit: junit.xml

nightly-convert:
  image: kicad/kicad:nightly
  stage: convert
  only:
    - schedules
  before_script:
    - sudo apt update -q && sudo apt install -qqy git
    - git config --global "http.${CI_SERVER_URL}.sslCAInfo" "$CI_SERVER_TLS_CA_FILE"
    - git clone --depth 1 https://gitlab.com/kicad/libraries/kicad-library-utils $CI_BUILDS_DIR/kicad-library-utils
  script:
    - find . -name "*.kicad_mod" -exec sed -i 's/\${KICAD6_3DMODEL_DIR}/\${KICAD7_3DMODEL_DIR}/g' {} \;
    - export LIB_NAME_MASK="*.pretty" LIB_TYPE=fp LIB_DEST="$CI_BUILDS_DIR/libraries" LIB_REMOTE_BRANCH=nightly-rolling
    - git clone --branch $LIB_REMOTE_BRANCH --depth 1 "https://token:$GITLAB_ACCESS_TOKEN@gitlab.com/kicad/libraries/kicad-footprints.git" $CI_BUILDS_DIR/libraries
    - mkdir -p $HOME/.config/kicad/7.0/colors
    - $CI_BUILDS_DIR/kicad-library-utils/scripts/migrate_libraries.sh
    - cd $CI_BUILDS_DIR/libraries/
    - git config user.name "CI Pipeline"
    - git config user.email "cipipeline@noreply.kicad.org"
    - git add -A && git commit -m "Update to master ${CI_COMMIT_SHA:0:12}"
    - git push origin HEAD:$LIB_REMOTE_BRANCH

screenshot:
  image: kicad/kicad:8.0
  stage: screenshot
  allow_failure: true
  when: manual
  only:
    refs:
      - merge_requests
    changes:
      - "**/*.kicad_mod"
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - sudo apt update -qq
    - sudo apt install curl inkscape python3 git -qqy --no-install-recommends
    - mkdir -p $HOME/.config/kicad/8.0/colors
    - git clone --depth 1 https://gitlab.com/kicad/libraries/kicad-library-utils $CI_BUILDS_DIR/kicad-library-utils
    - git config --global --add safe.directory $(realpath .)
  script:
    - $CI_BUILDS_DIR/kicad-library-utils/tools/gitlabci/screenshot_footprints.sh
  artifacts:
    expose_as: 'Screenshots'
    paths:
      - screenshots/

model:
  image: kicad/kicad:nightly-202404
  stage: model
  allow_failure: true
  when: manual
  only:
    refs:
      - merge_requests
    changes:
      - "**/*.kicad_mod"
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - sudo apt update -qq
    - sudo apt install curl python3 git -qqy --no-install-recommends
    - mkdir -p $HOME/.config/kicad/8.0/colors
    - git clone --depth 1 https://gitlab.com/kicad/libraries/kicad-library-utils $CI_BUILDS_DIR/kicad-library-utils
    - git clone --depth 1 https://gitlab.com/kicad/libraries/kicad-packages3D $CI_BUILDS_DIR/kicad-packages3D
    - git config --global --add safe.directory $(realpath .)
  script:
    - $CI_BUILDS_DIR/kicad-library-utils/tools/gitlabci/screenshot_model.sh
  artifacts:
    expose_as: 'Model'
    paths:
      - screenshots/

visual_diff:
  stage: diffs
  needs: []
  image: kicad/kicad:8.0
  allow_failure: true
  when: always
  only:
    refs:
      - merge_requests
    changes:
      - "**/*.kicad_mod"
  script:
    - echo -e "\e[0Ksection_start:`date +%s`:environment[collapsed=true]\r\e[0KEnvironment"
    - printenv
    - echo -e "\e[0Ksection_end:`date +%s`:environment\r\e[0K"
    - mkdir -p $HOME/.config/kicad/8.0/colors
    - sudo apt update -qq
    - sudo apt install curl python3 python3-pip -qqy --no-install-recommends
    - python3 -V
    - pip install --break-system-packages pygments wsdiff jinja2
    - $CI_BUILDS_DIR/kicad-library-utils/tools/gitlabci/visual_diff.sh
    - mkdir diffs
    - mv *.diff diffs/
  artifacts:
    expose_as: "Visual Diff"
    paths:
      - "diffs/"
    reports:
      dotenv: deploy.env
  #dependencies:
  #  - screenshot
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: $DYNAMIC_ENVIRONMENT_URL
