variables:
  PYTHONUNBUFFERED: "1"

3d-formatting:
  stage: Static Analysis
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  before_script:
    - python --version
    - python -m pip install --upgrade pip
    - pip install -e '.[dev]'
  script:
    - ./manage.sh 3d_format_check

.model:
  stage: 3D Generate
  needs: []
  rules:
    - when: manual
  before_script:
    - apt-get update -q -y
    - apt-get install -y libgl1-mesa-glx git fontconfig
  # We use the line below when running the validator but don't need it
  # or the time required to d/l and setup unless we run the validator
  #  - apt-get install -y build-essential libgl1-mesa-glx kicad
    - python --version
    - python -m pip install --upgrade pip
    - pip install -e '.[3d]'
  script:
    - cd '3d-model-generators'
    - ./generator.py --output_dir ./3dmodels --library $library --enable-vrml True
    # - sudo find / -iname 3dmodels > models_location.txt
    # - ./validator.py --unvalidated_dir /tmp/3dmodels --validated_dir /usr/share/kicad/3dmodels/ > audit_log.txt
    # - cat ./audit_log.txt
  artifacts:
    paths:
      - 3d-model-generators/3dmodels
      # - models_location.txt
      # - audit_log.txt
  # Avoid hanging the status of the pipeline on the success of this job
  allow_failure: true

.model_with_packages:
  extends:
    - .model
  script:
    - |
      cd '3d-model-generators'
      package_args=""
      for package in $packages
        do
          package_args="$package_args -p $package"
        done
    - echo "./generator.py --output_dir ./3dmodels --library $library $package_args"
    - ./generator.py --output_dir ./3dmodels --library $library $package_args

#
# 4UCON_17809
#
ucon_17809:
  variables:
    library: 4UCON_17809
  extends:
    - .model

#
# Altech
#
Altech:
  variables:
    library: Altech
  extends:
    - .model

#
# Battery
#
Battery:
  variables:
    library: Battery
  extends:
    - .model

#
# BGA_packages
#
BGA_packages:
  variables:
    library: BGA_packages
  extends:
    - .model

#
# Box_Headers directory
#
Box_Headers:
  variables:
    library: Box_Headers
  extends:
    - .model

#
# Button_Switch_Rotary
#
Button_Switch_Rotary:
  variables:
    library: Button_Switch_Rotary
  extends:
    - .model

#
# Button_Switch_Tactile
#
Button_Switch_Tactile:
  variables:
    library: Button_Switch_Tactile
  extends:
    - .model

#
# Buzzer_Beeper
#
Buzzer_Beeper:
  variables:
    library: Buzzer_Beeper
  extends:
    - .model

#
# C_Chip_SMD
#
C_Chip_SMD:
  variables:
    library: C_Chip_SMD
  extends:
    - .model

#
# C_Trimmer
#
C_Trimmer:
  variables:
    library: C_Trimmer
  extends:
    - .model

#
# Capacitor_THT
#
Capacitor_THT:
  variables:
    library: Capacitor_THT
  extends:
    - .model

#
# Connector_Audio
#
Connector_Audio:
  variables:
    library: Connector_Audio
  extends:
    - .model

#
# Connector_Coaxial
#
Connector_Coaxial:
  variables:
    library: Connector_Coaxial
  extends:
    - .model

#
# Connector_Dsub
#
Connector_Dsub:
  variables:
    library: Connector_Dsub
  extends:
    - .model

#
# Connector_FFC-FPC
#
Connector_FFC-FPC:
  variables:
    library: Connector_FFC-FPC
  extends:
    - .model

#
# Connector_Phoenix_SPT
#
Connector_Phoenix_SPT:
  variables:
    library: Connector_Phoenix_SPT
  extends:
    - .model

#
# Connector_PinHeader
#
Connector_PinHeader:
  variables:
    library: Connector_PinHeader
  extends:
    - .model
  timeout: 3 hours

#
# Connector_Stocko
#
Connector_Stocko:
  variables:
    library: Connector_Stocko
  extends:
    - .model

#
# Connector_USB
#
Connector_USB:
  variables:
    library: Connector_USB
  extends:
    - .model

#
# Connector_Wago_734
#
Connector_Wago_734:
  variables:
    library: Connector_Wago_734
  extends:
    - .model

#
# Connector_Wuerth_WR-PHD
#
Connector_Wuerth_WR-PHD:
  variables:
    library: Connector_Wuerth_WR-PHD
  extends:
    - .model

#
# Converter_ACDC
#
Converter_ACDC:
  variables:
    library: Converter_ACDC
  extends:
    - .model

#
# Converter_DCDC
#
Converter_DCDC:
  variables:
    library: Converter_DCDC
  extends:
    - .model

#
# CP_Radial_SMD
#
CP_Radial_SMD:
  variables:
    library: CP_Radial_SMD
  extends:
    - .model

#
# CP_Radial_THT
#
CP_Radial_THT:
  variables:
    library: CP_Radial_THT
  extends:
    - .model

#
# CP_Tantalum_SMD
#
CP_Tantalum_SMD:
  variables:
    library: CP_Tantalum_SMD
  extends:
    - .model

#
# CP_Tantalum_THT
#
CP_Tantalum_THT:
  variables:
    library: CP_Tantalum_THT
  extends:
    - .model

#
# Crystal
#
Crystal:
  variables:
    library: Crystal
  extends:
    - .model

#
# diodes_SMx_SMD
#
diodes_SMx_SMD:
  variables:
    library: diodes_SMx_SMD
  extends:
    - .model

#
# DIP_packages
#
DIP_packages:
  variables:
    library: DIP_packages
  extends:
    - .model

#
# DIP_parts
#
DIP_parts:
  variables:
    library: DIP_parts
  extends:
    - .model

#
# Directfet_SMD
#
Directfet_SMD:
  variables:
    library: Directfet_SMD
  extends:
    - .model

#
# Filter
#
Filter:
  variables:
    library: Filter
  extends:
    - .model

#
# Flat_Pin_packages
#
Flat_Pin_packages:
  variables:
    library: Flat_Pin_packages
  extends:
    - .model

#
# Fuse
#
Fuse:
  variables:
    library: Fuse
  extends:
    - .model

#
# GW_QFP_SOIC_SSOP_TSSOP_SOT
#
GW_QFP_SOIC_SSOP_TSSOP_SOT:
  variables:
    library: GW_QFP_SOIC_SSOP_TSSOP_SOT
  extends:
    - .model
  timeout: 3 hours

#
# Inductors_SMD
#
Inductors_SMD:
  variables:
    library: Inductors_SMD
  extends:
    - .model

#
# jst
#
jst:
  variables:
    library: jst
  extends:
    - .model

#
# L_Chip_SMD
#
L_Chip_SMD:
  variables:
    library: L_Chip_SMD
  extends:
    - .model

#
# LED_SMD
#
LED_SMD:
  variables:
    library: LED_SMD
  extends:
    - .model

#
# molex
#
molex:
  variables:
    library: molex
  extends:
    - .model

#
# Molex_5569
#
Molex_5569:
  variables:
    library: Molex_5569
  extends:
    - .model

#
# mounting_wuerth
#
mounting_wuerth:
  variables:
    library: mounting_wuerth
  extends:
    - .model

#
# OptoDevice
#
OptoDevice:
  variables:
    library: OptoDevice
  extends:
    - .model

#
# Package_SIP
#
Package_SIP:
  variables:
    library: Package_SIP
  extends:
    - .model

#
# phoenix_contact
#
phoenix_contact:
  variables:
    library: phoenix_contact
  extends:
    - .model

#
# Potentiometer_THT
#
Potentiometer_THT:
  variables:
    library: Potentiometer_THT
  extends:
    - .model

#
# QFN_packages
#
QFN_packages:
  variables:
    library: QFN_packages
  extends:
    - .model

#
# Relay_THT
#
Relay_THT:
  variables:
    library: Relay_THT
  extends:
    - .model

#
# Resistor_SMD
#
Resistor_SMD:
  variables:
    library: Resistor_SMD
  extends:
    - .model

#
# Resistor_THT
#
Resistor_THT:
  variables:
    library: Resistor_THT
  extends:
    - .model

#
# resistors_array_SMD
#
resistors_array_SMD:
  variables:
    library: resistors_array_SMD
  extends:
    - .model

#
# RF_Antenna_Chip_SMD
#
RF_Antenna_Chip_SMD:
  variables:
    library: RF_Antenna_Chip_SMD
  extends:
    - .model

#
# Standoff_FF_MF
#
Standoff_FF_MF:
  variables:
    library: Standoff_FF_MF
  extends:
    - .model

#
# Switch_SMD
#
Switch_SMD:
  variables:
    library: Switch_SMD
  extends:
    - .model

#
# TerminalBlock_Phoenix
#
TerminalBlock_Phoenix:
  variables:
    library: TerminalBlock_Phoenix
  extends:
    - .model

#
# TO_SOT_Packages_SMD_custom
#
TO_SOT_Packages_SMD_custom:
  variables:
    library: TO_SOT_Packages_SMD_custom
  extends:
    - .model

#
# Transformer_THT
#
Transformer_THT:
  variables:
    library: Transformer_THT
  extends:
    - .model

#
# Valves
#
Valves:
  variables:
    library: Valves
  extends:
    - .model

#
# Varistor
#
Varistor:
  variables:
    library: Varistor
  extends:
    - .model

#
# Connector_PinSocket
#
Connector_PinSocket_THT_1.00:
  variables:
    library: Connector_PinSocket
    packages: >
      THT-1x1.00mm_Vertical
  extends:
    - .model_with_packages
Connector_PinSocket_SMD_1.00:
  variables:
    library: Connector_PinSocket
    packages: >
      SMD-1x1.00mm_Vertical_Right
      SMD-1x1.00mm_Vertical_Left
      SMD-2x1.00mm_Vertical
  extends:
    - .model_with_packages
Connector_PinSocket_THT_1.27:
  variables:
    library: Connector_PinSocket
    packages: >
      THT-1x1.27mm_Vertical
      THT-2x1.27mm_Vertical
      THT-2x1.27mm_Horizontal
  extends:
    - .model_with_packages
Connector_PinSocket_SMD_1.27:
  variables:
    library: Connector_PinSocket
    packages: >
      SMD-1x1.27mm_Vertical_Right
      SMD-1x1.27mm_Vertical_Left
      SMD-2x1.27mm_Vertical
  extends:
    - .model_with_packages
Connector_PinSocket_THT_2.00:
  variables:
    library: Connector_PinSocket
    packages: >
      THT-1x2.00mm_Vertical
      THT-2x2.00mm_Vertical
      THT-1x2.00mm_Horizontal
      THT-2x2.00mm_Horizontal
  extends:
    - .model_with_packages
Connector_PinSocket_SMD_2.00:
  variables:
    library: Connector_PinSocket
    packages: >
      SMD-1x2.00mm_Vertical_Right
      SMD-1x2.00mm_Vertical_Left
      SMD-2x2.00mm_Vertical
  extends:
    - .model_with_packages
Connector_PinSocket_THT_2.54:
  variables:
    library: Connector_PinSocket
    packages: >
      THT-1x2.54mm_Vertical
      THT-2x2.54mm_Vertical
      THT-1x2.54mm_Horizontal
      THT-2x2.54mm_Horizontal
  extends:
    - .model_with_packages
Connector_PinSocket_SMD_2.54:
  variables:
    library: Connector_PinSocket
    packages: >
      SMD-1x2.54mm_Vertical_Right
      SMD-1x2.54mm_Vertical_Left
      SMD-2x2.54mm_Vertical
  extends:
    - .model_with_packages
